version: '3.8'

services:
  web:
    build:
      context: .
      target: deps
    command: pnpm dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
    networks:
      - app-network

  # Add more services as needed (e.g., database, cache, etc.)

networks:
  app-network:
    driver: bridge 